carte_niveau_1 = [
    "                                                                                          XXXXXXXXXX      XXX                                                                                                                                                                                                                                                                             ",
    "                                                                                                          XXX                                                                                                                                                                                                                                                                                      ",
    "                                                                                                          XXX                      XX                                                                                                                                                                                                                                                     ",
    "   P                                                                                                      XXX      XXXX                         XX                                              XX                                                                                                                           XXXX                                                           ",
    "                                      XXXXX                                     XXXX      XXXXXXXXXX      XXX      XXXX                                                 XX                                                                                                                                                                                                                 ",
    "  XX                                  XXXXX                                XXXX      XXXX XXXXXXXXXX      XXXX     XXXX   XX                                                         XX                                                                                                                               X                 X                                                    ",
    "     X                           XXX  XXXXX      XXXX                XXXX                 XXXXXXXXXX      XXX      XXXX           XX               XX              XX                                       XX                                                                                                                                                                          ",
    "        X                        XXX  XXXXX           XXXX      XXXX                      XXXXXXXXXX              XXXXX                 XX                   XX             XX                                     XXXXXXXXXX    XXXXXXXXX     XXXXXXXX      XXXXXXX      XXXXX      XXXX      XXX      XX      X                                                                         ",
    "           X          XXXXXXXX   XXX  XXXXX  XXXX          XXXX                           XXXXXXXXXX               XXXX               XX      XX           XX                                      XX                                                                                                                                                                                                    ",
    "  XXX  XXX            XXXXXXXX   XXXXXXXXXX                                               XXXXXXXXXX               XXXX     XX                       XX                 XX            XX                                                                                                                                                                                                             ",
    "XXXXX  XXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                               XXXXXXXXXXXXXXXXXXXX     XXXX                                           XX             XX            XX           XX                                                                                                                                         XXXXXXX                                             ",
]
